version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: 'axios'
      - dependency-name: 'cross-fetch'
      - dependency-name: 'got'
      - dependency-name: 'isomorphic-fetch'
      - dependency-name: 'node-fetch'
      - dependency-name: 'readable-stream-2'
      - dependency-name: 'undici'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
